[tool.poetry]
name = "home-buying-decision-analysis"
version = "0.1.0"
description = ""
authors = ["Matt Camp <matt@aicampground.com>"]
readme = "README.md"
package-mode = false 

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
redfin = "^0.1.1"
homeharvest = "^0.4.3"
walkscore-api = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
