info = {"message": "fix: LEAP-237: Patch ORM Leak vulnerability in open source (#5012)", "commit": "f931d9d129002f54a495995774ce7384174cef5c", "date": "2023/11/08 13:52:43", "branch": "", "version": "1.9.2.post0+0.gf931d9d.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
