apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glusterfs-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # early, before apps that need storage
spec:
  project: platform

  source:
    repoURL: https://github.com/levindecaro/csi-driver-glusterfs.git
    targetRevision: main
    path: deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: glusterfs-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
