apiVersion: v1
kind: Namespace
metadata:
  name: glusterfs-storage
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: glusterfs-storage
spec:
  ports:
    - name: glusterfs
      port: 1
      targetPort: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: glusterfs-storage
subsets:
  - addresses:
      - ip: 10.8.0.176
      - ip: 10.8.0.189
    ports:
      - name: glusterfs
        port: 1
