apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # only matters vs other *Applications* in app-of-apps
spec:
  project: platform

  sources:
    # Helm chart
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 32.2.0
      helm:
        valueFiles:
          - $values/apps/traefik/values.yaml

    # Values ref for $values/...
    - repoURL: https://gitlab.com/usmcamp0811/dotfiles.git
      targetRevision: nixos
      ref: values

    # Manifests in your repo (IngressRoutes, ExternalSecret, etc.)
    - repoURL: https://gitlab.com/usmcamp0811/dotfiles.git
      targetRevision: nixos
      path: apps/traefik
      directory:
        recurse: true
        exclude: |
          values.yaml
          **/.gitkeep

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-k8s

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
