stages:
  - update_flake
  - build_systems
  - deploy

.setup_ssh:
  script:
    - |
      echo "Authenticating with Vault..."
      vault write auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID"
      export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
      export sshkey=$(vault kv get -field="sshkey" "secret/campground/gitlab-runner")
      mkdir -p ~/.ssh
      eval "$(ssh-agent -s)"
      echo "$sshkey" | ssh-add -

update-flake:
  stage: update_flake
  tags:
    - nix
  script:
    - |
      [ "$CI_PIPELINE_SOURCE" = "schedule" ] && git rm flake.lock && nix flake update || true;
  artifacts:
    paths:
      - flake.lock
    expire_in: 1 hour
  rules:
    - if: '$BUILD_SYSTEMS == "true"'

.build_job_template: &build_job_template
  stage: build_systems
  tags:
    - nix
  script:
    - |
      echo "Authenticating with Vault..."
      vault write auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID"
      export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
      export sshkey=$(vault kv get -field="sshkey" "secret/campground/gitlab-runner")
      mkdir -p ~/.ssh
      eval "$(ssh-agent -s)"
      echo "$sshkey" | ssh-add -
      ssh-keyscan reckless >> ~/.ssh/known_hosts
      nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1
      nix-copy-closure --to root@${SYSTEM} ./result
  needs:
    - job: update-flake
  resource_group: build_sequential
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always
      allow_failure: false

butler:
  <<: *build_job_template
  variables:
    SYSTEM: "butler"

daly:
  <<: *build_job_template
  variables:
    SYSTEM: "daly"

lucas:
  <<: *build_job_template
  variables:
    SYSTEM: "lucas"

chesty:
  <<: *build_job_template
  variables:
    SYSTEM: "chesty"

webb:
  <<: *build_job_template
  variables:
    SYSTEM: "webb"

reckless:
  <<: *build_job_template
  variables:
    SYSTEM: "reckless"

.deploy_job_template: &deploy_job_template
  stage: deploy
  tags:
    - nix
  script:
    - |
      echo "Authenticating with Vault..."
      vault write auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID"
      export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
      eval "$(ssh-agent -s)"
      vault kv get -field="lucas_CI_SERVER_URL" "secret/campground/gitlab-runner"
      sshkey=$(vault kv get -field="sshkey" "secret/campground/gitlab-runner")
      mkdir -p ~/.ssh
      echo "$sshkey" | ssh-add -
    - |
      ssh-keyscan $SYSTEM >> ~/.ssh/known_hosts
      nix run nixpkgs#figlet -- -t -c "$SYSTEM" | nix run nixpkgs#lolcat
      deploy --hostname $SYSTEM .#$SYSTEM
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
      allow_failure: false

butler_deploy:
  <<: *deploy_job_template
  variables:
    SYSTEM: "butler"

daly_deploy:
  <<: *deploy_job_template
  variables:
    SYSTEM: "daly"

lucas_deploy:
  <<: *deploy_job_template
  variables:
    SYSTEM: "lucas"

chesty_deploy:
  <<: *deploy_job_template
  variables:
    SYSTEM: "chesty"

webb_deploy:
  <<: *deploy_job_template
  variables:
    SYSTEM: "webb"

reckless_deploy:
  <<: *deploy_job_template
  variables:
    SYSTEM: "reckless"

.deploy_hosting_template: &deploy_hosting_template
  stage: deploy
  script:
    - |
      echo "Authenticating with Vault..."
      vault write auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID"
      export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
      SYSTEMS=$(get-lan-pub-systems $DEPLOY_TYPE)
      echo $SYSTEMS
      eval "$(ssh-agent -s)"
      vault kv get -field="lucas_CI_SERVER_URL" "secret/campground/gitlab-runner"
      sshkey=$(vault kv get -field="sshkey" "secret/campground/gitlab-runner")
      mkdir -p ~/.ssh

      echo "$sshkey" | ssh-add -
      for SYSTEM in $SYSTEMS; do
        ssh-keyscan $SYSTEM >> ~/.ssh/known_hosts
        nix run nixpkgs#figlet -- -t -c "$SYSTEM" | nix run nixpkgs#lolcat
        deploy --hostname $SYSTEM .#$SYSTEM
      done
  tags:
    - nix

deploy_public_hosting:
  <<: *deploy_hosting_template
  variables:
    DEPLOY_TYPE: "public"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - "**/public-hosting/default.nix"
      when: always
      allow_failure: false

deploy_lan_hosting:
  <<: *deploy_hosting_template
  variables:
    DEPLOY_TYPE: "lan"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - "**/lan-hosting/default.nix"
      when: always
      allow_failure: false
