stages:
  - update
  - build

variables:
  SYSTEM: "lucas"

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
    allow_failure: false

update-flake:
  stage: update
  tags:
    - nix
  only:
    - nixos
  script:
    - git rm flake.lock
    - nix flake update
  artifacts:
    paths:
      - flake.lock
    expire_in: 1 hour

build-butler:
  stage: build
  variables:
    SYSTEM: "butler"
  tags:
    - nix
  only:
    - nixos
  script:
    - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1;
    - nix run github:zhaofengli/attic\#attic-client push campground ./result
  needs:
    - update-flake

build-daly:
  stage: build
  variables:
    SYSTEM: "daly"
  tags:
    - nix
  only:
    - nixos
  script:
    - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1;
    - nix run github:zhaofengli/attic\#attic-client push campground ./result
  needs:
    - update-flake
    - build-butler

build-lucas:
  stage: build
  variables:
    SYSTEM: "lucas"
  tags:
    - nix
  only:
    - nixos
  script:
    - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1;
    - nix run github:zhaofengli/attic\#attic-client push campground ./result
  needs:
    - update-flake
    - build-daly

build-chesty:
  stage: build
  variables:
    SYSTEM: "chesty"
  tags:
    - nix
  only:
    - nixos
  script:
    - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1;
    - nix run github:zhaofengli/attic\#attic-client push campground ./result
  needs:
    - update-flake
    - build-lucas

build-webb:
  stage: build
  variables:
    SYSTEM: "webb"
  tags:
    - nix
  only:
    - nixos
  script:
    - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1;
    - nix run github:zhaofengli/attic\#attic-client push campground ./result
  needs:
    - update-flake
    - build-chesty

build-reckless:
  stage: build
  variables:
    SYSTEM: "reckless"
  tags:
    - nix
  only:
    - nixos
  script:
    - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1;
    - nix run github:zhaofengli/attic\#attic-client push campground ./result
  needs:
    - update-flake
    - build-webb
