stages:
  - update_flake
  - build_systems
  - deploy_hosting

.setup_ssh:
  script:
    - |
      echo "Authenticating with Vault..."
      vault write auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID"
      export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
      export sshkey=$(vault kv get -field="sshkey" "secret/campground/gitlab-runner")
      mkdir -p ~/.ssh
      eval "$(ssh-agent -s)"
      echo "$sshkey" | ssh-add -

update-flake:
  stage: update_flake
  tags:
    - nix
  script:
    - git rm flake.lock
    - nix flake update
  artifacts:
    paths:
      - flake.lock
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

.build_job_template: &build_job_template
  stage: build_systems
  tags:
    - nix
  script:
    - |
      ssh-keyscan reckless >> ~/.ssh/known_hosts
      nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel -j 1
      nix-copy-closure --to root@${SYSTEM} ./result
  needs:
    - update-flake
  resource_group: build_sequential
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

butler:
  <<: *build_job_template
  variables:
    SYSTEM: "butler"

daly:
  <<: *build_job_template
  variables:
    SYSTEM: "daly"

lucas:
  <<: *build_job_template
  variables:
    SYSTEM: "lucas"

chesty:
  <<: *build_job_template
  variables:
    SYSTEM: "chesty"

webb:
  <<: *build_job_template
  variables:
    SYSTEM: "webb"

reckless:
  <<: *build_job_template
  variables:
    SYSTEM: "reckless"

# .deploy_hosting_template: &deploy_hosting_template
#   stage: deploy_hosting
#   extends:
#     - .setup_ssh
#   script:
#     - |
#       for SYSTEM in $SYSTEMS; do
#         ssh-keyscan $SYSTEM >> ~/.ssh/known_hosts
#         nix run nixpkgs#figlet -- -t -c "$SYSTEM" | nix run nixpkgs#lolcat
#         deploy --hostname $SYSTEM .#$SYSTEM
#       done
#   tags:
#     - nix

deploy_public_hosting:
  stage: deploy_hosting
  variables:
    DEPLOY_TYPE: "public"
  extends:
    - .setup_ssh
  tags:
    - nix
  script:
    - |
      for SYSTEM in $SYSTEMS; do
        ssh-keyscan $SYSTEM >> ~/.ssh/known_hosts
        nix run nixpkgs#figlet -- -t -c "$SYSTEM" | nix run nixpkgs#lolcat
        deploy --hostname $SYSTEM .#$SYSTEM
      done
  rules:
    - changes:
        - "**/public-hosting/default.nix"

deploy_lan_hosting:
  stage: deploy_hosting
  variables:
    DEPLOY_TYPE: "lan"
  extends:
    - .setup_ssh
  tags:
    - nix
  script:
    - |
      for SYSTEM in $SYSTEMS; do
        ssh-keyscan $SYSTEM >> ~/.ssh/known_hosts
        nix run nixpkgs#figlet -- -t -c "$SYSTEM" | nix run nixpkgs#lolcat
        deploy --hostname $SYSTEM .#$SYSTEM
      done
  rules:
    - changes:
        - "**/lan-hosting/default.nix"

