{ lib
, writeText
, writeShellApplication
, gum
, inputs
, pkgs
, hosts ? { }
, ...
}:
let
  inherit (lib) mapAttrsToList concatStringsSep;
  inherit (lib.campground) override-meta;
  pname = "phpLDAPadmin";
  version = "1.2.6.6";

  config-php = pkgs.writeText "config.php" ''
    <?php
    /** NOTE **
     ** Make sure that <?php is the FIRST line of this file!
     ** IE: There should NOT be any blank lines or spaces BEFORE <?php
     **/

     /*********************************************
      * Useful important configuration overrides  *
      *********************************************/

     /* If you are asked to put PLA in debug mode, this is how you do it: */
     $config->custom->debug['level'] = 0;
     $config->custom->debug['syslog'] = true;
     #  $config->custom->debug['file'] = '/tmp/pla_debug.log';

    /**
     * The phpLDAPadmin config file
     * See: http://phpldapadmin.sourceforge.net/wiki/index.php/Config.php
     */

    /* The temporary storage directory where we will put jpegPhoto data
       This directory must be readable and writable by your web server. */
     $config->custom->jpeg['tmpdir'] = '/var/www/tmp';

     /* phpLDAPadmin can encrypt the content of sensitive cookies if you set this
       to a big random string. */

    /*
     * Autogenerated value will be automatically added by phpldapadmin/startup.sh
     */
     $config->custom->session['blowfish'] = 'IJ?uUbMFim)0MJwm./}m#@PH?7WDoMSZUZ1 ?4s/1gK6]P$HxTiQf_4N.W*mn7K';


    /*********************************************
     * Appearance                                *
     *********************************************/
    /* Hide the warnings for invalid objectClasses/attributes in templates. */
    $config->custom->appearance['hide_template_warning'] = true;



    /*********************************************
     * User-friendly attribute translation       *
     *********************************************/

    /* Use this array to map attribute names to user friendly names. For example, if
       you don't want to see "facsimileTelephoneNumber" but rather "Fax". */
    // $config->custom->appearance['friendly_attrs'] = array();
    $config->custom->appearance['friendly_attrs'] = array(
      'facsimileTelephoneNumber' => 'Fax',
      'gid'                      => 'Group',
      'mail'                     => 'Email',
      'telephoneNumber'          => 'Telephone',
      'uid'                      => 'User Name',
      'userPassword'             => 'Password'
    );


    /*********************************************
     * Define your LDAP servers in this section  *
     *********************************************/

    $servers = new Datastore();

    /*
     * Autogenerated servers variables will come here
     */
    $servers->newServer('ldap_pla');
    $servers->setValue('server','name', getenv('LDAP_SERVER_NAME') ?: 'default_name');
    $servers->setValue('server','host', getenv('LDAP_SERVER_HOST') ?: 'default_host');
  '';
  phpLDAPadmin = pkgs.stdenv.mkDerivation {
    name = "${pname}-${version}";
    src = pkgs.fetchurl {
      url = "https://github.com/leenooks/phpLDAPadmin/archive/refs/tags/${version}.tar.gz";
      sha256 = "sha256-eowCphHmCqZxPRz4Y9+sljfiPD9NQB6l5H2+KyLUiVo=";
    };

    buildInputs = [ pkgs.php ];

    installPhase = ''
      mkdir -p $out/var/www
      cp -r . $out/var/www/${pname}
      cp ${config-php} $out/var/www/${pname}/config/config.php
    '';
  };
  new-meta = with lib; {
    description = "A web-based LDAP administration tool";
    license = licenses.asl20;
    maintainers = with maintainers; [ mattcamp ];
  };
in
override-meta new-meta phpLDAPadmin
