{ host ? "", options, config, lib, pkgs, ... }:

with lib;
with lib.campground;
let cfg = config.campground.services.akhq;
in {
  options.campground.services.akhq = with types; {
    enable = mkBoolOpt false "Whether or not to enable kafka configuration.";
    connection-name = mkOpt str "campground"
        "Name of the connection";
    bootstrap-server = mkOpt str "${host}:9092" "Kafka server address";
    port = mkOpt int 8435 "Port to Host the Apache Kafka HQ server.";
  };

  config = mkIf cfg.enable {
    networking.firewall.interfaces."podman-+".allowedUDPPorts = [ 53 ];
    networking.firewall.interfaces."podman-+".allowedTCPPorts = [ 9092 9093 ];
    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      # dockerCompat = true;
      defaultNetwork.settings = {
        # Required for container networking to be able to use names.
        dns_enabled = true;
      };
    };
    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."akhq-akhq" = {
      image = "tchiotludo/akhq";
      environment = {
        AKHQ_CONFIGURATION = "akhq:
      connections:
        ${cfg.connection-name}:
          properties:
            bootstrap.servers: ${cfg.bootstrap-server}

    ";
      };
      ports = [
        "${builtins.toString cfg.port}:8080/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=akhq"
        "--network=akhq_default"
      ];
    };

    systemd.services."podman-akhq-akhq" = {
      serviceConfig = {
        Restart = "always";
      };
      after = [
        "podman-network-akhq_default.service"
      ];
      requires = [
        "podman-network-akhq_default.service"
      ];
      partOf = [
        "podman-compose-akhq-root.target"
      ];
      wantedBy = [
        "podman-compose-akhq-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-akhq_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "${pkgs.podman}/bin/podman network rm -f akhq_default";
      };
      script = ''
        podman network inspect akhq_default || podman network create akhq_default
      '';
      partOf = [ "podman-compose-akhq-root.target" ];
      wantedBy = [ "podman-compose-akhq-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-akhq-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

  };
}
