apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/platform-project.yaml
  - apps/argocd-self.yaml
  - apps/storage.yaml
  - apps/external-secrets.yaml
  - apps/vault-backend.yaml
  - apps/metallb.yaml
  - apps/traefik.yaml
