{ pkgs, config, lib, nixos-hardware, nixosModules, ... }:
with lib;
with lib.campground;
let
  newUser = name: {
    isNormalUser = true;
    createHome = true;
    home = "/home/${name}";
    shell = pkgs.zsh;
  };
in
{
  # hardware.nix should probably be autogenerated if you don't know what you are doing.
  imports = [ ./hardware.nix ];

  campground = {
    archetypes = {
      laptop = enabled;
      server = {
        enable = true;
        hostId = "eb2d6e11";
        keyfile-url =
          "http://10.8.0.1:1234/zfs-keyfile"; # optional for autounlocking
      };
    };
    nfs.client = { enable = true; };
    suites = {
      common = enabled;
      desktop.enable = mkForce false;
      lan-hosting = {
        enable = true;
        interface = "enp7s0";
      };
    };
    user = {
      name = "mcamp";
      fullName = "Matt Camp";
      email = "matt@aicampground.com";
      extraGroups = [ "wheel" ];
    };

    services = {
      ldap-client = { enable = mkForce false; };
      # borgbackup = {
      #   enable = true;
      #   jobs = {
      #     "daly_campground" = {
      #       paths = [ "/persist" ];
      #       repo = "mcamp@reckless:/mnt/backups/daly";
      #       startAt = "daily";
      #     };
      #     "daly_rsync" = {
      #       paths = [ "/persist" ];
      #       repo = "de3288@de3288.rsync.net:/data2/home/de3288/backups/daly";
      #       startAt = "daily";
      #     };
      #   };
      # };
      searx = {
        enable = true;
        port = 8181;
      };
      campground-blog = enabled;

      zfs-key-server = {
        enable = true;
        interface = "enp7s0";
        tang-servers = [
          "http://webb:1234"
          "http://chesty:1234"
          "http://lucas:1234"
          "http://reckless:1234"
        ];
        port = 8123;
      };
      user-secrets = {
        enable = true;
        users = { mcamp = { files = [ "id_ed25519" "passwords" ]; }; };
      };
      vault = {
        enable = true;
        ui = true;
        storage = {
          backend = "raft";
          config = ''
            node_id = "vault-node-ermy"
            retry_join {
              leader_api_addr = "http://chesty:8200"
            }
            retry_join {
              leader_api_addr = "http://mattis:8200"
            }
            retry_join {
              leader_api_addr = "http://lucas:8200"
            }
          '';
        };
        settings = ''
          cluster_addr = "http://ermy:8201" 
          api_addr = "http://ermy:8200"
        '';

        policies = builtins.foldl'
          (policies: file:
            policies // {
              "${snowfall.path.get-file-name-without-extension file}" = file;
            })
          { }
          (builtins.filter (snowfall.path.has-file-extension "hcl")
            (builtins.map
              (path:
                ../daly/vault/policies + "/${
                builtins.baseNameOf (builtins.unsafeDiscardStringContext path)
              }")
              (snowfall.fs.get-files ../daly/vault/policies)));
      };
      vault-agent = {
        enable = true;
        settings = {
          vault = {
            # address = "https://vault.lan.aicampground.com";
            address = "http://lucas:8200";
            role-id = "/var/lib/vault/ermy/role-id";
            secret-id = "/var/lib/vault/ermy/secret-id";
          };
        };
      };
    };
  };

  system.stateVersion = "23.05";
}
