[application]

[web.app]

# HTML title tag content
title = "webb-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.ai.campground"
publisher = "AICampground"
out_dir = "./dist"
