apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.k8s.aicampground.com`)
    services:
    - name: longhorn-frontend
      port: 80
  tls:
    certResolver: cloudflare
