---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-glusterfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.campground.ai/kubernetes
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "true"
