apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kiali-oidc
  namespace: istio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: kiali
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        oidc-secret: "{{ .OIDC_CLIENT_SECRET }}"

  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: kiali
        property: OIDC_CLIENT_SECRET
