auth:
  strategy: openid
  openid:
    client_id: "wbf92G5cpQGxRQMSNTih7bhy3Upuu1nFvrh11Qhj" # OIDC client_id (public)
    issuer_uri: https://auth.aicampground.com/application/o/kiali/
    scopes:
      - openid
      - profile
      - email
    username_claim: preferred_username

    # Unless your Kubernetes API server is ALSO configured for OIDC and you want per-user RBAC,
    # keep this true so Kiali doesn't try to map IdP users to K8s RBAC.
    disable_rbac: true

server:
  web_fqdn: istio.k8s.aicampground.com
  web_root: /
  web_schema: https

deployment:
  logger:
    log_level: info
    log_format: text
    sampler_rate: "1"
    time_field_format: 2006-01-02T15:04:05Z07:00

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

external_services:
  prometheus:
    url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
  istio:
    root_namespace: istio-system
  grafana:
    enabled: false
  tracing:
    enabled: false
