# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@bufbuild/protobuf-2.3.0" = {
      name = "_at_bufbuild_slash_protobuf";
      packageName = "@bufbuild/protobuf";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@bufbuild/protobuf/-/protobuf-2.3.0.tgz";
        sha512 = "WK6zH4MtBp/uesX8KGCnwDDRVnEVHUvwjsigKXcSR57Oo8Oyv1vRS9qyUlSP+6KWRl5z8tNAU5qpf3QodeVYxA==";
      };
    };
    "buffer-builder-0.2.0" = {
      name = "buffer-builder";
      packageName = "buffer-builder";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-builder/-/buffer-builder-0.2.0.tgz";
        sha512 = "7VPMEPuYznPSoR21NE1zvd2Xna6c/CloiZCfcMXR1Jny6PjX0N4Nsa38zcBFo/FMK+BlA+FLKbJCQ0i2yxp+Xg==";
      };
    };
    "colorjs.io-0.5.2" = {
      name = "colorjs.io";
      packageName = "colorjs.io";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorjs.io/-/colorjs.io-0.5.2.tgz";
        sha512 = "twmVoizEW7ylZSN32OgKdXRmo1qg+wT5/6C3xu5b9QsWzSFAhHLn2xd8ro0diCsKfCj1RdaTP/nrcW+vAoQPIw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "immutable-5.1.2" = {
      name = "immutable";
      packageName = "immutable";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-5.1.2.tgz";
        sha512 = "qHKXW1q6liAk1Oys6umoaZbDRqjcjgSrbnrifHsfsttza7zcvRAsL7mMV6xWcyhwQy7Xj5v4hhbr6b+iDYwlmQ==";
      };
    };
    "rxjs-7.8.2" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.8.2.tgz";
        sha512 = "dhKf903U/PQZY6boNNtAGdWbG85WAbjT/1xYoZIC7FAY0yWapOBQVsVrDl58W86//e1VpMNBtRV4MaXfdMySFA==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "sync-child-process-1.0.2" = {
      name = "sync-child-process";
      packageName = "sync-child-process";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sync-child-process/-/sync-child-process-1.0.2.tgz";
        sha512 = "8lD+t2KrrScJ/7KXCSyfhT3/hRq78rC0wBFqNJXv3mZyn6hW2ypM05JmlSvtqRbeq6jqA94oHbxAr2vYsJ8vDA==";
      };
    };
    "sync-message-port-1.1.3" = {
      name = "sync-message-port";
      packageName = "sync-message-port";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sync-message-port/-/sync-message-port-1.1.3.tgz";
        sha512 = "GTt8rSKje5FilG+wEdfCkOcLL7LWqpMlr2c3LRuKt/YXxcJ52aGSbGBAdI4L3aaqfrBt6y711El53ItyH1NWzg==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "varint-6.0.0" = {
      name = "varint";
      packageName = "varint";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-6.0.0.tgz";
        sha512 = "cXEIW6cfr15lFv563k4GuVuW/fiwjknytD37jIOLSdSWuOI6WnO/oKwmP2FQTU2l01LP8/M5TSAJpzUaGe3uWg==";
      };
    };
  };
  args = {
    name = "sass-embedded";
    packageName = "sass-embedded";
    version = "1.88.0";
    src = ./.;
    dependencies = [
      sources."@bufbuild/protobuf-2.3.0"
      sources."buffer-builder-0.2.0"
      sources."colorjs.io-0.5.2"
      sources."has-flag-4.0.0"
      sources."immutable-5.1.2"
      sources."rxjs-7.8.2"
      sources."supports-color-8.1.1"
      sources."sync-child-process-1.0.2"
      sources."sync-message-port-1.1.3"
      sources."tslib-2.8.1"
      sources."varint-6.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Node.js library that communicates with Embedded Dart Sass using the Embedded Sass protocol";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
