apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  addresses:
    - 10.8.40.100-10.8.40.255
  autoAssign: true
