# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "NIXROOT/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D9F2-E5F0";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "NIXROOT/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "NIXROOT/persist";
      fsType = "zfs";
    };

  fileSystems."/mnt/chestyfs" =
    { device = "ChestyPoolr/chestyfs";
      fsType = "zfs";
    };

  fileSystems."/mnt/backups/webb" =
    { device = "ChestyPoolr/backups/webb";
      fsType = "zfs";
    };

  fileSystems."/mnt/backups/daly" =
    { device = "ChestyPoolr/backups/daly";
      fsType = "zfs";
    };

  fileSystems."/mnt/backups/butler" =
    { device = "ChestyPoolr/backups/butler";
      fsType = "zfs";
    };

  fileSystems."/mnt/backups/lucas" =
    { device = "ChestyPoolr/backups/lucas";
      fsType = "zfs";
    };

  # sudo zfs create -V 16G -o compression=zle -o logbias=throughput -o sync=always -o primarycache=metadata -o secondarycache=none NIXROOT/swap
  # sudo mkswap -f /dev/zvol/NIXROOT/swap
  # sudo swapon /dev/zvol/NIXROOT/swap

  swapDevices = [
    {
      device = "/dev/zvol/NIXROOT/swap";
      randomEncryption.enable = true;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0u1u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
