{ lib
, config
, pkgs
, ...
}:
with lib;
with lib.campground; let
  cfg = config.campground.services.k0s;
  inherit (pkgs.campground) k0s;

  configFile =
    if cfg.configText != ""
    then pkgs.writeText "k0s.template.yaml" cfg.configText
    else
    # TODO: make the ports a variable that is sync between modules
      pkgs.writeText "k0s.yaml" ''
        # Generated by the k0s module
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: Cluster
        metadata:
          name: ${cfg.clusterName}
        spec:
          network:
            provider: custom
            podCIDR: 10.244.0.0/16
          api:
            address: ''${HOST_IP}
            externalAddress: ${cfg.apiAddress}
            k0sApiPort: ${toString cfg.k0sApiPort}
            port: ${toString cfg.kubeAPIPort}
            sans:
              - ${cfg.apiAddress}
          extensions:
            storage:
              create_default_storage_class: true
              type: openebs_local_storage
          installConfig:
            users:
              etcdUser: ${cfg.users.etcdUser}
              kineUser: ${cfg.users.kineUser}
              konnectivityUser: ${cfg.users.konnectivityUser}
              kubeAPIserverUser: ${cfg.users.kubeAPIserverUser}
              kubeSchedulerUser: ${cfg.users.kubeSchedulerUser}
          konnectivity:
            adminPort: ${toString cfg.konnectivityAdminAPIPort}
            agentPort: ${toString cfg.konnectivityAgentAPIPort}
          podSecurityPolicy:
            defaultPolicy: 00-k0s-privileged
          storage:
            type: etcd
            etcd:
              peerAddress: ''${HOST_IP}
          telemetry:
            enabled: false
      '';
in
{
  options.campground.services.k0s = {
    enable =
      mkEnableOption (lib.mdDoc "Enable the k0s Kubernetes distribution.");

    package = mkPackageOption pkgs "k0s" { };

    role = mkOption {
      type = types.enum [ "controller" "controller+worker" "worker" "single" ];
      default = "single";
      description = ''
        The role of the node.
      '';
    };

    domain = mkOption {
      default = "k8s.lan.aicampground.com";
      type = types.str;
      description = ''
        Domain name for the control plane
      '';
    };

    k0sApiPort = mkOption {
      default = 9445;
      type = types.int;
      description = ''
        K0s API Port
      '';
    };

    kubeAPIPort = mkOption {
      default = 6443;
      type = types.int;
      description = ''
        Kubernete API Port
      '';
    };
    konnectivityAgentAPIPort = mkOption {
      default = 8132;
      type = types.int;
      description = ''
        Konnectivity agentPort
      '';
    };
    konnectivityAdminAPIPort = mkOption {
      default = 8133;
      type = types.int;
      description = ''
        Konnectivity adminPort
      '';
    };

    apiAddress = mkOption {
      # No default, has to be provided
      type = types.str;
      description = ''
        Required. Local address on which to bind an API.
      '';
    };

    interface = mkOpt types.str "eno1" "Interface to use for the LAN Instance";
    apiSans = mkOption {
      type = types.listOf types.str;
      description = ''
        Required. List of additional addresses to push to API servers serving the certificate.
      '';
    };

    clusterName = mkOption {
      type = types.str;
      default = "k0s";
      description = ''
        The name of the cluster.
      '';
    };

    isLeader = mkOption {
      type = types.bool;
      default = false;
      description = ''
        The leader is used to generate the join tokens or makes the kubernetes api accessible.
      '';
    };

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/k0s";
    };

    configText = mkOption {
      default = "";
      type = types.str;
      description = ''
        The configuration file in YAML format.
        A default will be generated if unset.
      '';
    };

    users = {
      etcdUser = mkOption {
        type = types.str;
        default = "etcd";
      };
      kineUser = mkOption {
        type = types.str;
        default = "kube-apiserver";
      };
      konnectivityUser = mkOption {
        type = types.str;
        default = "konnectivity-server";
      };
      kubeAPIserverUser = mkOption {
        type = types.str;
        default = "kube-apiserver";
      };
      kubeSchedulerUser = mkOption {
        type = types.str;
        default = "kube-scheduler";
      };
    };

    role-id =
      mkOpt types.str
        config.campground.services.vault-agent.settings.vault.role-id
        "Absolute path to the Vault role-id";
    secret-id =
      mkOpt types.str
        config.campground.services.vault-agent.settings.vault.secret-id
        "Absolute path to the Vault secret-id";
    vault-path =
      mkOpt types.str "secret/campground/k0s"
        "The Vault path to the KV containing the k0s secrets.";
    vault-address = mkOption {
      type = types.str;
      default = config.campground.services.vault-agent.settings.vault.address;
      description = "The address of your Vault";
    };
    kvVersion = mkOption {
      type = types.enum [ "v1" "v2" ];
      default = "v2";
      description = "KV store version";
    };
  };
  config = mkIf cfg.enable {
    environment.systemPackages = with pkgs; [
      openiscsi
      nfs-utils
      cilium-cli
      campground.k0s
    ];

    systemd.network.networks."10-${cfg.interface}" = {
      matchConfig.Name = cfg.interface;
      networkConfig = {
        DHCP = "yes";
      };
      extraConfig = ''
        [Network]
        ManageForeignRoutingPolicyRules=no
      '';
    };

    systemd.services = mkMerge [
      {
        cleanup-cni = {
          description = "Clean up CNI state before starting k0s";
          before = [ "k0s-controller.service" "k0s-worker.service" ];
          wantedBy = [ "multi-user.target" ];
          serviceConfig = {
            Type = "oneshot";
            ExecStart = pkgs.writeShellScript "cleanup-cni" ''
              set -e
              echo "Cleaning up old CNI state..."

              # CNI state dirs
              rm -rf /var/lib/cni /run/cni

              # Remove orphaned veth pairs
              for i in $(${pkgs.iproute2}/bin/ip -o link show | ${pkgs.gawk}/bin/awk -F': ' '{print $2}' | grep '^veth'); do
                ${pkgs.iproute2}/bin/ip link delete $i || true
              done
            '';
          };
        };
      }
      (mkIf (cfg.role == "controller" || cfg.role == "controller+worker") {
        # (mkIf cfg.isLeader {
        "k0s-controller-store-tokens" = {
          description = "Generate k0s join tokens and store in Vault";
          after = [
            "k0s-controller.service"
            "vault-agent.service"
            "network-online.target"
          ];

          requires = [ "k0s-controller.service" ];
          wantedBy = [ "multi-user.target" ];
          serviceConfig = {
            Type = "oneshot";
            User = "root";
            ExecStart = pkgs.writeShellScript "store-k0s-tokens" ''
              set -e

              echo "Waiting for k0s to be fully running..."

              until ${cfg.package}/bin/k0s status &>/dev/null; do
                sleep 5
              done

              echo "k0s is up, generating join tokens..."

              WORKER_TOKEN="$(${cfg.package}/bin/k0s token create --role worker --expiry=0)"
              CONTROLLER_TOKEN="$(${cfg.package}/bin/k0s token create --role controller --expiry=0)"
              ADMIN_KUBECONFIG="$(${cfg.package}/bin/k0s kubeconfig admin)"

              VAULT_PATH="${cfg.vault-path}"
              export VAULT_ADDR="${cfg.vault-address}"
              HOSTNAME=${config.networking.hostName}
              echo "WHAT THE FUCK IS GOING ON HERE $HOSTNAME"
              ROLE_ID=$(cat /var/lib/vault/$HOSTNAME/role-id)
              SECRET_ID=$(cat /var/lib/vault/$HOSTNAME/secret-id)

              echo "Logging in to Vault using AppRole..."
              VAULT_TOKEN=$(${pkgs.vault}/bin/vault write -field=token auth/approle/login role_id="$ROLE_ID" secret_id="$SECRET_ID")
              export VAULT_TOKEN
              echo "Reading certs from ${cfg.dataDir}/pki..."

              CA_KEY=$(<${cfg.dataDir}/pki/ca.key)
              CA_CRT=$(<${cfg.dataDir}/pki/ca.crt)
              SA_KEY=$(<${cfg.dataDir}/pki/sa.key)
              SA_PUB=$(<${cfg.dataDir}/pki/sa.pub)
              ETCD_CA_KEY=$(<${cfg.dataDir}/pki/etcd/ca.key)
              ETCD_CA_CRT=$(<${cfg.dataDir}/pki/etcd/ca.crt)

              echo "Storing tokens, kubeconfig, and certs in Vault..."
              ${pkgs.vault}/bin/vault kv put "$VAULT_PATH" \
                controller="$CONTROLLER_TOKEN" \
                worker="$WORKER_TOKEN" \
                admin_kubeconfig="$ADMIN_KUBECONFIG" \
                ca_key="$CA_KEY" \
                ca_crt="$CA_CRT" \
                sa_key="$SA_KEY" \
                sa_pub="$SA_PUB" \
                etcd_ca_key="$ETCD_CA_KEY" \
                etcd_ca_crt="$ETCD_CA_CRT"

              echo "Stored all k0s secrets in Vault at $VAULT_PATH"
            '';
            RemainAfterExit = true;
          };
        };
      })
      (mkIf ((cfg.role == "controller" || cfg.role == "controller+worker") && (!cfg.isLeader)) {
        "get-k0s-controller-token" = {
          description = "Get k0s join tokens from Vault";
          after = [
            "vault-agent.service"
            "network-online.target"
          ];
          wantedBy = [
            "multi-user.target"
          ];
          serviceConfig = {
            Type = "oneshot";
            User = "root";
            ExecStart = pkgs.writeShellScript "get-k0s-tokens" ''
              set -e

              mkdir -p ${cfg.dataDir}/pki/etcd

              cp /tmp/detsys-vault/k0s-token-controller ${cfg.dataDir}/k0s-token-controller
              cp /tmp/detsys-vault/ca.key ${cfg.dataDir}/pki/ca.key
              cp /tmp/detsys-vault/ca.crt ${cfg.dataDir}/pki/ca.crt
              cp /tmp/detsys-vault/sa.key ${cfg.dataDir}/pki/sa.key
              cp /tmp/detsys-vault/sa.pub ${cfg.dataDir}/pki/sa.pub
              cp /tmp/detsys-vault/etcd-ca.key ${cfg.dataDir}/pki/etcd/ca.key
              cp /tmp/detsys-vault/etcd-ca.crt ${cfg.dataDir}/pki/etcd/ca.crt

              chown root:root ${cfg.dataDir}/k0s-token-controller
              chmod 0400 ${cfg.dataDir}/k0s-token-controller

              chown root:root ${cfg.dataDir}/pki/ca.key
              chmod 0400 ${cfg.dataDir}/pki/ca.key

              chown root:root ${cfg.dataDir}/pki/ca.crt
              chmod 0444 ${cfg.dataDir}/pki/ca.crt

              chown root:root ${cfg.dataDir}/pki/sa.key
              chmod 0400 ${cfg.dataDir}/pki/sa.key

              chown root:root ${cfg.dataDir}/pki/sa.pub
              chmod 0444 ${cfg.dataDir}/pki/sa.pub

              chown root:root ${cfg.dataDir}/pki/etcd/ca.key
              chmod 0400 ${cfg.dataDir}/pki/etcd/ca.key

              chown root:root ${cfg.dataDir}/pki/etcd/ca.crt
              chmod 0444 ${cfg.dataDir}/pki/etcd/ca.crt
            '';

            RemainAfterExit = true;
          };
        };
      })
      (mkIf (cfg.role == "worker" || cfg.role == "controller+worker") {
        "get-k0s-worker-token" = {
          description = "Get k0s join tokens from Vault";
          after = [
            "vault-agent.service"
            "network-online.target"
          ];
          wantedBy = [
            "multi-user.target"
          ];
          serviceConfig = {
            Type = "oneshot";
            User = "root";
            ExecStart = pkgs.writeShellScript "get-k0s-tokens" ''
              set -e

              mkdir -p ${cfg.dataDir}/pki/etcd

              cp /tmp/detsys-vault/k0s-token-worker ${cfg.dataDir}/k0s-token-worker
              cp /tmp/detsys-vault/ca.key ${cfg.dataDir}/pki/ca.key
              cp /tmp/detsys-vault/ca.crt ${cfg.dataDir}/pki/ca.crt
              cp /tmp/detsys-vault/sa.key ${cfg.dataDir}/pki/sa.key
              cp /tmp/detsys-vault/sa.pub ${cfg.dataDir}/pki/sa.pub
              cp /tmp/detsys-vault/etcd-ca.key ${cfg.dataDir}/pki/etcd/ca.key
              cp /tmp/detsys-vault/etcd-ca.crt ${cfg.dataDir}/pki/etcd/ca.crt

              chown root:root ${cfg.dataDir}/k0s-token-worker
              chmod 0400 ${cfg.dataDir}/k0s-token-worker

              chown root:root ${cfg.dataDir}/pki/ca.key
              chmod 0400 ${cfg.dataDir}/pki/ca.key

              chown root:root ${cfg.dataDir}/pki/ca.crt
              chmod 0444 ${cfg.dataDir}/pki/ca.crt

              chown root:root ${cfg.dataDir}/pki/sa.key
              chmod 0400 ${cfg.dataDir}/pki/sa.key

              chown root:root ${cfg.dataDir}/pki/sa.pub
              chmod 0444 ${cfg.dataDir}/pki/sa.pub

              chown root:root ${cfg.dataDir}/pki/etcd/ca.key
              chmod 0400 ${cfg.dataDir}/pki/etcd/ca.key

              chown root:root ${cfg.dataDir}/pki/etcd/ca.crt
              chmod 0444 ${cfg.dataDir}/pki/etcd/ca.crt
            '';

            RemainAfterExit = true;
          };
        };
      })
      (mkIf (cfg.role == "worker" || cfg.role == "controller+worker") {
        "k0s-worker" = {
          description = "k0s Worker - Zero Friction Kubernetes";
          documentation = [ "https://docs.k0sproject.io" ];
          path = with pkgs; [ kmod util-linux mount ];
          requires = [ "get-k0s-worker-token.service" ];
          after = [ "network-online.target" "get-k0s-worker-token.service" ];
          wants = [ "network-online.target" "get-k0s-worker-token.service" ];
          wantedBy = [ "multi-user.target" ];
          startLimitIntervalSec = 5;
          startLimitBurst = 10;
          serviceConfig = {
            RestartSec = 120;
            Delegate = "yes";
            KillMode = "process";
            LimitCORE = "infinity";
            TasksMax = "infinity";
            TimeoutStartSec = 0;
            LimitNOFILE = 999999;
            Restart = "always";
            ExecStart =
              "${cfg.package}/bin/k0s worker --data-dir=${cfg.dataDir}"
              + optionalString (!cfg.isLeader)
                " --token-file=${cfg.dataDir}/k0s-token-worker";
            # ExecStartPre = pkgs.writeShellScript "umount-k8s" ''
            #   umount -l /var/lib/kubelet/pods/*/volumes/*/* || true
            #   umount -l /run/k0s/containerd/io.containerd.* || true
            # '';
          };
          # preStart = ''
          # '';
          # unitConfig = mkIf (!cfg.isLeader) {
          #   ConditionPathExists = "${cfg.dataDir}/k0s-token-worker";
          # };
        };
      })
      (mkIf (cfg.role == "controller" || cfg.role == "controller+worker") {
        "k0s-controller" = {
          description = "k0s Controller - Zero Friction Kubernetes";
          documentation = [ "https://docs.k0sproject.io" ];
          path = with pkgs; [ kmod util-linux mount iptables ];

          after = [ "network-online.target" "get-k0s-controller-token.service" "cleanup-cni.service" ];
          wants = [ "network-online.target" "get-k0s-controller-token.service" ];
          wantedBy = [ "multi-user.target" ];
          startLimitIntervalSec = 5;
          startLimitBurst = 10;
          serviceConfig = {
            RestartSec = 120;
            Delegate = "yes";
            KillMode = "process";
            LimitCORE = "infinity";
            TasksMax = "infinity";
            TimeoutStartSec = 0;
            LimitNOFILE = 999999;
            Restart = "always";
            # ExecStart = ''
            #   ${cfg.package}/bin/k0s controller --data-dir=${cfg.dataDir} --config=${cfg.dataDir}/k0s.yaml
            #   ${
            #     optionalString (!cfg.isLeader) " --token-file=${cfg.dataDir}/k0s-token-controller"
            #   }
            # '';
            ExecStart = ''
              ${cfg.package}/bin/k0s controller --data-dir=${cfg.dataDir}${
                optionalString cfg.isLeader " --config=${cfg.dataDir}/k0s.yaml"
              }${
                optionalString (!cfg.isLeader) " --token-file=${cfg.dataDir}/k0s-token-controller"
              }
            '';
            ExecStartPre = pkgs.writeShellScript "umount-k8s" ''
              umount -l /var/lib/kubelet/pods/*/volumes/*/* || true
              umount -l /run/k0s/containerd/io.containerd.* || true
            '';
          };
          preStart = ''
            HOST_IP=$(${pkgs.iproute2}/bin/ip -4 addr show ${cfg.interface} | ${pkgs.gawk}/bin/awk '/inet / {print $2}' | ${pkgs.coreutils}/bin/cut -d/ -f1 | ${pkgs.coreutils}/bin/head -n1)
            export HOST_IP
            mkdir -p ${cfg.dataDir}
            ${pkgs.envsubst}/bin/envsubst < ${configFile} > ${cfg.dataDir}/k0s.yaml
          '';

          # unitConfig = mkIf (!cfg.isLeader) {
          #   ConditionPathExists = "/tmp/detsys-vault/k0s-token-controller";
          # };
        };
      })
    ];
    boot.kernelModules = [
      "ip_tables"
      "ip_set"
      "xt_set"
      "nf_conntrack"
      "nf_nat"
      "nf_conntrack_ipv4"
      "nf_nat_ipv4"
      "nf_conntrack_ipv6"
      "nf_nat_ipv6"
      "bpf"
    ];
    boot.kernelParams = [ "cgroup_enable=memory" "cgroup_enable=cpuset" ];

    users.users =
      concatMapAttrs
        (_name: value: {
          ${value} = {
            isSystemUser = true;
            group = "users";
            home = "${cfg.dataDir}";
          };
        })
        cfg.users;
    campground.services.vault-agent.services = {
      get-k0s-worker-token =
        mkIf
          (
            (cfg.role == "worker" || cfg.role == "controller+worker" || cfg.role == "single")
            && !cfg.isLeader
          )
          {
            settings = {
              vault.address = cfg.vault-address;
              auto_auth = {
                method = [
                  {
                    type = "approle";
                    config = {
                      role_id_file_path = cfg.role-id;
                      secret_id_file_path = cfg.secret-id;
                      remove_secret_id_file_after_reading = false;
                    };
                  }
                ];
              };
            };
            secrets = {
              file = {
                files = {
                  "k0s-token-worker" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.worker }}{{ else }}{{ .Data.data.worker }}{{ end }}{{ end }}'';
                    permissions = "0400"; # Make the script executable
                    change-action = "restart";
                  };
                  "ca.key" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.ca_key }}{{ else }}{{ .Data.data.ca_key }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "ca.crt" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.ca_crt }}{{ else }}{{ .Data.data.ca_crt }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "sa.key" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.sa_key }}{{ else }}{{ .Data.data.sa_key }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "sa.pub" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.sa_pub }}{{ else }}{{ .Data.data.sa_pub }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "etcd-ca.key" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.etcd_ca_key }}{{ else }}{{ .Data.data.etcd_ca_key }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "etcd-ca.crt" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.etcd_ca_crt }}{{ else }}{{ .Data.data.etcd_ca_crt }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                };
              };
            };
          };
      get-k0s-controller-token =
        mkIf
          (
            (cfg.role == "controller" || cfg.role == "controller+worker" || cfg.role == "single")
            && !cfg.isLeader
          )
          {
            settings = {
              vault.address = cfg.vault-address;
              auto_auth = {
                method = [
                  {
                    type = "approle";
                    config = {
                      role_id_file_path = cfg.role-id;
                      secret_id_file_path = cfg.secret-id;
                      remove_secret_id_file_after_reading = false;
                    };
                  }
                ];
              };
            };
            secrets = {
              file = {
                files = {
                  "k0s-token-controller" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.controller }}{{ else }}{{ .Data.data.controller }}{{ end }}{{ end }}'';
                    permissions = "0400"; # Make the script executable
                    change-action = "restart";
                  };
                  "ca.key" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.ca_key }}{{ else }}{{ .Data.data.ca_key }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "ca.crt" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.ca_crt }}{{ else }}{{ .Data.data.ca_crt }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "sa.key" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.sa_key }}{{ else }}{{ .Data.data.sa_key }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "sa.pub" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.sa_pub }}{{ else }}{{ .Data.data.sa_pub }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "etcd-ca.key" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.etcd_ca_key }}{{ else }}{{ .Data.data.etcd_ca_key }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                  "etcd-ca.crt" = {
                    text = ''
                      {{ with secret "${cfg.vault-path}" }}{{ if eq "${cfg.kvVersion}" "v1" }}{{ .Data.etcd_ca_crt }}{{ else }}{{ .Data.data.etcd_ca_crt }}{{ end }}{{ end }}'';
                    permissions = "0400";
                    change-action = "restart";
                  };
                };
              };
            };
          };
    };
  };
}
# Largely adapted from https://github.com/johbo/k0s-nix/tree/main

